name: Update Major Release Tag

on:
  release:
    types: [created]

# Explicitly set permissions
permissions:
  contents: write

jobs:
  movetag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # Use the default GITHUB_TOKEN
        token: ${{ github.token }}

    - name: Get major version num and update tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION_NO_V=${VERSION#v}
        MAJOR=${VERSION_NO_V%%.*}
        if [[ $VERSION == v* ]]; then
          MAJOR_TAG="v${MAJOR}"
        else
          MAJOR_TAG="${MAJOR}"
        fi
        
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        git tag -fa "${MAJOR_TAG}" -m "Update major version tag to ${VERSION}"
        git push origin "${MAJOR_TAG}" --force
        echo "Updated major version tag to ${MAJOR_TAG}"
