name: Update Major Release Tag

on:
  release:
    types: [created]

jobs:
  movetag:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Get major version num and update tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        # Remove 'v' prefix if it exists
        VERSION_NO_V=${VERSION#v}
        MAJOR=${VERSION_NO_V%%.*}
        # Add 'v' prefix back if original version had it
        if [[ $VERSION == v* ]]; then
          MAJOR_TAG="v${MAJOR}"
        else
          MAJOR_TAG="${MAJOR}"
        fi
        git config --global user.name '${{ vars.GH_USERNAME }}'
        git config --global user.email '${{ vars.GH_EMAIL }}'
        git tag -fa "${MAJOR_TAG}" -m "Update major version tag to ${VERSION}"
        git push origin "${MAJOR_TAG}" --force 
        echo "Updated major version tag to ${MAJOR_TAG}"
